// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: prism_switch.proto

#ifndef PROTOBUF_INCLUDED_prism_5fswitch_2eproto
#define PROTOBUF_INCLUDED_prism_5fswitch_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_prism_5fswitch_2eproto

namespace protobuf_prism_5fswitch_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable
      serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_prism_5fswitch_2eproto
namespace prism {
class PrismSwitchAddReq;
class PrismSwitchAddReqDefaultTypeInternal;
extern PrismSwitchAddReqDefaultTypeInternal
    _PrismSwitchAddReq_default_instance_;
class PrismSwitchChangeOwnerReq;
class PrismSwitchChangeOwnerReqDefaultTypeInternal;
extern PrismSwitchChangeOwnerReqDefaultTypeInternal
    _PrismSwitchChangeOwnerReq_default_instance_;
class PrismSwitchDeleteReq;
class PrismSwitchDeleteReqDefaultTypeInternal;
extern PrismSwitchDeleteReqDefaultTypeInternal
    _PrismSwitchDeleteReq_default_instance_;
class PrismSwitchLockReq;
class PrismSwitchLockReqDefaultTypeInternal;
extern PrismSwitchLockReqDefaultTypeInternal
    _PrismSwitchLockReq_default_instance_;
class PrismSwitchReply;
class PrismSwitchReplyDefaultTypeInternal;
extern PrismSwitchReplyDefaultTypeInternal _PrismSwitchReply_default_instance_;
} // namespace prism
namespace google {
namespace protobuf {
template <>
::prism::PrismSwitchAddReq *
Arena::CreateMaybeMessage<::prism::PrismSwitchAddReq>(Arena *);
template <>
::prism::PrismSwitchChangeOwnerReq *
Arena::CreateMaybeMessage<::prism::PrismSwitchChangeOwnerReq>(Arena *);
template <>
::prism::PrismSwitchDeleteReq *
Arena::CreateMaybeMessage<::prism::PrismSwitchDeleteReq>(Arena *);
template <>
::prism::PrismSwitchLockReq *
Arena::CreateMaybeMessage<::prism::PrismSwitchLockReq>(Arena *);
template <>
::prism::PrismSwitchReply *
Arena::CreateMaybeMessage<::prism::PrismSwitchReply>(Arena *);
} // namespace protobuf
} // namespace google
namespace prism {

// ===================================================================

class PrismSwitchAddReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prism.PrismSwitchAddReq)
                                                              */
{
public:
  PrismSwitchAddReq();
  virtual ~PrismSwitchAddReq();

  PrismSwitchAddReq(const PrismSwitchAddReq &from);

  inline PrismSwitchAddReq &
  operator=(const PrismSwitchAddReq &from)
  {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  PrismSwitchAddReq(PrismSwitchAddReq &&from) noexcept : PrismSwitchAddReq()
  {
    *this = ::std::move(from);
  }

  inline PrismSwitchAddReq &
  operator=(PrismSwitchAddReq &&from) noexcept
  {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from)
        InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  static const ::google::protobuf::Descriptor *descriptor();
  static const PrismSwitchAddReq &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const PrismSwitchAddReq *
  internal_default_instance()
  {
    return reinterpret_cast<const PrismSwitchAddReq *>(
        &_PrismSwitchAddReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;

  void Swap(PrismSwitchAddReq *other);
  friend void
  swap(PrismSwitchAddReq &a, PrismSwitchAddReq &b)
  {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PrismSwitchAddReq *
  New() const final
  {
    return CreateMaybeMessage<PrismSwitchAddReq>(NULL);
  }

  PrismSwitchAddReq *
  New(::google::protobuf::Arena *arena) const final
  {
    return CreateMaybeMessage<PrismSwitchAddReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const PrismSwitchAddReq &from);
  void MergeFrom(const PrismSwitchAddReq &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int
  GetCachedSize() const final
  {
    return _cached_size_.Get();
  }

private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrismSwitchAddReq *other);

private:
  inline ::google::protobuf::Arena *
  GetArenaNoVirtual() const
  {
    return NULL;
  }
  inline void *
  MaybeArenaPtr() const
  {
    return NULL;
  }

public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 peer_addr = 1;
  void clear_peer_addr();
  static const int kPeerAddrFieldNumber = 1;
  ::google::protobuf::uint32 peer_addr() const;
  void set_peer_addr(::google::protobuf::uint32 value);

  // uint32 peer_port = 2;
  void clear_peer_port();
  static const int kPeerPortFieldNumber = 2;
  ::google::protobuf::uint32 peer_port() const;
  void set_peer_port(::google::protobuf::uint32 value);

  // uint32 virtual_addr = 3;
  void clear_virtual_addr();
  static const int kVirtualAddrFieldNumber = 3;
  ::google::protobuf::uint32 virtual_addr() const;
  void set_virtual_addr(::google::protobuf::uint32 value);

  // uint32 virtual_port = 4;
  void clear_virtual_port();
  static const int kVirtualPortFieldNumber = 4;
  ::google::protobuf::uint32 virtual_port() const;
  void set_virtual_port(::google::protobuf::uint32 value);

  // uint32 owner_addr = 5;
  void clear_owner_addr();
  static const int kOwnerAddrFieldNumber = 5;
  ::google::protobuf::uint32 owner_addr() const;
  void set_owner_addr(::google::protobuf::uint32 value);

  // uint32 owner_port = 6;
  void clear_owner_port();
  static const int kOwnerPortFieldNumber = 6;
  ::google::protobuf::uint32 owner_port() const;
  void set_owner_port(::google::protobuf::uint32 value);

  // uint64 owner_mac = 7;
  void clear_owner_mac();
  static const int kOwnerMacFieldNumber = 7;
  ::google::protobuf::uint64 owner_mac() const;
  void set_owner_mac(::google::protobuf::uint64 value);

  // bool lock = 8;
  void clear_lock();
  static const int kLockFieldNumber = 8;
  bool lock() const;
  void set_lock(bool value);

  // @@protoc_insertion_point(class_scope:prism.PrismSwitchAddReq)
private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 peer_addr_;
  ::google::protobuf::uint32 peer_port_;
  ::google::protobuf::uint32 virtual_addr_;
  ::google::protobuf::uint32 virtual_port_;
  ::google::protobuf::uint32 owner_addr_;
  ::google::protobuf::uint32 owner_port_;
  ::google::protobuf::uint64 owner_mac_;
  bool lock_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_prism_5fswitch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PrismSwitchChangeOwnerReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prism.PrismSwitchChangeOwnerReq)
                                                                      */
{
public:
  PrismSwitchChangeOwnerReq();
  virtual ~PrismSwitchChangeOwnerReq();

  PrismSwitchChangeOwnerReq(const PrismSwitchChangeOwnerReq &from);

  inline PrismSwitchChangeOwnerReq &
  operator=(const PrismSwitchChangeOwnerReq &from)
  {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  PrismSwitchChangeOwnerReq(PrismSwitchChangeOwnerReq &&from) noexcept
      : PrismSwitchChangeOwnerReq()
  {
    *this = ::std::move(from);
  }

  inline PrismSwitchChangeOwnerReq &
  operator=(PrismSwitchChangeOwnerReq &&from) noexcept
  {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from)
        InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  static const ::google::protobuf::Descriptor *descriptor();
  static const PrismSwitchChangeOwnerReq &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const PrismSwitchChangeOwnerReq *
  internal_default_instance()
  {
    return reinterpret_cast<const PrismSwitchChangeOwnerReq *>(
        &_PrismSwitchChangeOwnerReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;

  void Swap(PrismSwitchChangeOwnerReq *other);
  friend void
  swap(PrismSwitchChangeOwnerReq &a, PrismSwitchChangeOwnerReq &b)
  {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PrismSwitchChangeOwnerReq *
  New() const final
  {
    return CreateMaybeMessage<PrismSwitchChangeOwnerReq>(NULL);
  }

  PrismSwitchChangeOwnerReq *
  New(::google::protobuf::Arena *arena) const final
  {
    return CreateMaybeMessage<PrismSwitchChangeOwnerReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const PrismSwitchChangeOwnerReq &from);
  void MergeFrom(const PrismSwitchChangeOwnerReq &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int
  GetCachedSize() const final
  {
    return _cached_size_.Get();
  }

private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrismSwitchChangeOwnerReq *other);

private:
  inline ::google::protobuf::Arena *
  GetArenaNoVirtual() const
  {
    return NULL;
  }
  inline void *
  MaybeArenaPtr() const
  {
    return NULL;
  }

public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 peer_addr = 1;
  void clear_peer_addr();
  static const int kPeerAddrFieldNumber = 1;
  ::google::protobuf::uint32 peer_addr() const;
  void set_peer_addr(::google::protobuf::uint32 value);

  // uint32 peer_port = 2;
  void clear_peer_port();
  static const int kPeerPortFieldNumber = 2;
  ::google::protobuf::uint32 peer_port() const;
  void set_peer_port(::google::protobuf::uint32 value);

  // uint32 owner_addr = 3;
  void clear_owner_addr();
  static const int kOwnerAddrFieldNumber = 3;
  ::google::protobuf::uint32 owner_addr() const;
  void set_owner_addr(::google::protobuf::uint32 value);

  // uint32 owner_port = 4;
  void clear_owner_port();
  static const int kOwnerPortFieldNumber = 4;
  ::google::protobuf::uint32 owner_port() const;
  void set_owner_port(::google::protobuf::uint32 value);

  // uint64 owner_mac = 5;
  void clear_owner_mac();
  static const int kOwnerMacFieldNumber = 5;
  ::google::protobuf::uint64 owner_mac() const;
  void set_owner_mac(::google::protobuf::uint64 value);

  // bool unlock = 6;
  void clear_unlock();
  static const int kUnlockFieldNumber = 6;
  bool unlock() const;
  void set_unlock(bool value);

  // @@protoc_insertion_point(class_scope:prism.PrismSwitchChangeOwnerReq)
private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 peer_addr_;
  ::google::protobuf::uint32 peer_port_;
  ::google::protobuf::uint32 owner_addr_;
  ::google::protobuf::uint32 owner_port_;
  ::google::protobuf::uint64 owner_mac_;
  bool unlock_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_prism_5fswitch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PrismSwitchDeleteReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prism.PrismSwitchDeleteReq)
                                                                 */
{
public:
  PrismSwitchDeleteReq();
  virtual ~PrismSwitchDeleteReq();

  PrismSwitchDeleteReq(const PrismSwitchDeleteReq &from);

  inline PrismSwitchDeleteReq &
  operator=(const PrismSwitchDeleteReq &from)
  {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  PrismSwitchDeleteReq(PrismSwitchDeleteReq &&from) noexcept
      : PrismSwitchDeleteReq()
  {
    *this = ::std::move(from);
  }

  inline PrismSwitchDeleteReq &
  operator=(PrismSwitchDeleteReq &&from) noexcept
  {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from)
        InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  static const ::google::protobuf::Descriptor *descriptor();
  static const PrismSwitchDeleteReq &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const PrismSwitchDeleteReq *
  internal_default_instance()
  {
    return reinterpret_cast<const PrismSwitchDeleteReq *>(
        &_PrismSwitchDeleteReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;

  void Swap(PrismSwitchDeleteReq *other);
  friend void
  swap(PrismSwitchDeleteReq &a, PrismSwitchDeleteReq &b)
  {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PrismSwitchDeleteReq *
  New() const final
  {
    return CreateMaybeMessage<PrismSwitchDeleteReq>(NULL);
  }

  PrismSwitchDeleteReq *
  New(::google::protobuf::Arena *arena) const final
  {
    return CreateMaybeMessage<PrismSwitchDeleteReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const PrismSwitchDeleteReq &from);
  void MergeFrom(const PrismSwitchDeleteReq &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int
  GetCachedSize() const final
  {
    return _cached_size_.Get();
  }

private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrismSwitchDeleteReq *other);

private:
  inline ::google::protobuf::Arena *
  GetArenaNoVirtual() const
  {
    return NULL;
  }
  inline void *
  MaybeArenaPtr() const
  {
    return NULL;
  }

public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 peer_addr = 1;
  void clear_peer_addr();
  static const int kPeerAddrFieldNumber = 1;
  ::google::protobuf::uint32 peer_addr() const;
  void set_peer_addr(::google::protobuf::uint32 value);

  // uint32 peer_port = 2;
  void clear_peer_port();
  static const int kPeerPortFieldNumber = 2;
  ::google::protobuf::uint32 peer_port() const;
  void set_peer_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:prism.PrismSwitchDeleteReq)
private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 peer_addr_;
  ::google::protobuf::uint32 peer_port_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_prism_5fswitch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PrismSwitchLockReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prism.PrismSwitchLockReq)
                                                               */
{
public:
  PrismSwitchLockReq();
  virtual ~PrismSwitchLockReq();

  PrismSwitchLockReq(const PrismSwitchLockReq &from);

  inline PrismSwitchLockReq &
  operator=(const PrismSwitchLockReq &from)
  {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  PrismSwitchLockReq(PrismSwitchLockReq &&from) noexcept : PrismSwitchLockReq()
  {
    *this = ::std::move(from);
  }

  inline PrismSwitchLockReq &
  operator=(PrismSwitchLockReq &&from) noexcept
  {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from)
        InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  static const ::google::protobuf::Descriptor *descriptor();
  static const PrismSwitchLockReq &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const PrismSwitchLockReq *
  internal_default_instance()
  {
    return reinterpret_cast<const PrismSwitchLockReq *>(
        &_PrismSwitchLockReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;

  void Swap(PrismSwitchLockReq *other);
  friend void
  swap(PrismSwitchLockReq &a, PrismSwitchLockReq &b)
  {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PrismSwitchLockReq *
  New() const final
  {
    return CreateMaybeMessage<PrismSwitchLockReq>(NULL);
  }

  PrismSwitchLockReq *
  New(::google::protobuf::Arena *arena) const final
  {
    return CreateMaybeMessage<PrismSwitchLockReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const PrismSwitchLockReq &from);
  void MergeFrom(const PrismSwitchLockReq &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int
  GetCachedSize() const final
  {
    return _cached_size_.Get();
  }

private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrismSwitchLockReq *other);

private:
  inline ::google::protobuf::Arena *
  GetArenaNoVirtual() const
  {
    return NULL;
  }
  inline void *
  MaybeArenaPtr() const
  {
    return NULL;
  }

public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 peer_addr = 1;
  void clear_peer_addr();
  static const int kPeerAddrFieldNumber = 1;
  ::google::protobuf::uint32 peer_addr() const;
  void set_peer_addr(::google::protobuf::uint32 value);

  // uint32 peer_port = 2;
  void clear_peer_port();
  static const int kPeerPortFieldNumber = 2;
  ::google::protobuf::uint32 peer_port() const;
  void set_peer_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:prism.PrismSwitchLockReq)
private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 peer_addr_;
  ::google::protobuf::uint32 peer_port_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_prism_5fswitch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PrismSwitchReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prism.PrismSwitchReply)
                                                             */
{
public:
  PrismSwitchReply();
  virtual ~PrismSwitchReply();

  PrismSwitchReply(const PrismSwitchReply &from);

  inline PrismSwitchReply &
  operator=(const PrismSwitchReply &from)
  {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  PrismSwitchReply(PrismSwitchReply &&from) noexcept : PrismSwitchReply()
  {
    *this = ::std::move(from);
  }

  inline PrismSwitchReply &
  operator=(PrismSwitchReply &&from) noexcept
  {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from)
        InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  static const ::google::protobuf::Descriptor *descriptor();
  static const PrismSwitchReply &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const PrismSwitchReply *
  internal_default_instance()
  {
    return reinterpret_cast<const PrismSwitchReply *>(
        &_PrismSwitchReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;

  void Swap(PrismSwitchReply *other);
  friend void
  swap(PrismSwitchReply &a, PrismSwitchReply &b)
  {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PrismSwitchReply *
  New() const final
  {
    return CreateMaybeMessage<PrismSwitchReply>(NULL);
  }

  PrismSwitchReply *
  New(::google::protobuf::Arena *arena) const final
  {
    return CreateMaybeMessage<PrismSwitchReply>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const PrismSwitchReply &from);
  void MergeFrom(const PrismSwitchReply &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int
  GetCachedSize() const final
  {
    return _cached_size_.Get();
  }

private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrismSwitchReply *other);

private:
  inline ::google::protobuf::Arena *
  GetArenaNoVirtual() const
  {
    return NULL;
  }
  inline void *
  MaybeArenaPtr() const
  {
    return NULL;
  }

public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // sint32 error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:prism.PrismSwitchReply)
private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 error_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_prism_5fswitch_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// PrismSwitchAddReq

// uint32 peer_addr = 1;
inline void
PrismSwitchAddReq::clear_peer_addr()
{
  peer_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchAddReq::peer_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.peer_addr)
  return peer_addr_;
}
inline void
PrismSwitchAddReq::set_peer_addr(::google::protobuf::uint32 value)
{

  peer_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.peer_addr)
}

// uint32 peer_port = 2;
inline void
PrismSwitchAddReq::clear_peer_port()
{
  peer_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchAddReq::peer_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.peer_port)
  return peer_port_;
}
inline void
PrismSwitchAddReq::set_peer_port(::google::protobuf::uint32 value)
{

  peer_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.peer_port)
}

// uint32 virtual_addr = 3;
inline void
PrismSwitchAddReq::clear_virtual_addr()
{
  virtual_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchAddReq::virtual_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.virtual_addr)
  return virtual_addr_;
}
inline void
PrismSwitchAddReq::set_virtual_addr(::google::protobuf::uint32 value)
{

  virtual_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.virtual_addr)
}

// uint32 virtual_port = 4;
inline void
PrismSwitchAddReq::clear_virtual_port()
{
  virtual_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchAddReq::virtual_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.virtual_port)
  return virtual_port_;
}
inline void
PrismSwitchAddReq::set_virtual_port(::google::protobuf::uint32 value)
{

  virtual_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.virtual_port)
}

// uint32 owner_addr = 5;
inline void
PrismSwitchAddReq::clear_owner_addr()
{
  owner_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchAddReq::owner_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.owner_addr)
  return owner_addr_;
}
inline void
PrismSwitchAddReq::set_owner_addr(::google::protobuf::uint32 value)
{

  owner_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.owner_addr)
}

// uint32 owner_port = 6;
inline void
PrismSwitchAddReq::clear_owner_port()
{
  owner_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchAddReq::owner_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.owner_port)
  return owner_port_;
}
inline void
PrismSwitchAddReq::set_owner_port(::google::protobuf::uint32 value)
{

  owner_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.owner_port)
}

// uint64 owner_mac = 7;
inline void
PrismSwitchAddReq::clear_owner_mac()
{
  owner_mac_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64
PrismSwitchAddReq::owner_mac() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.owner_mac)
  return owner_mac_;
}
inline void
PrismSwitchAddReq::set_owner_mac(::google::protobuf::uint64 value)
{

  owner_mac_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.owner_mac)
}

// bool lock = 8;
inline void
PrismSwitchAddReq::clear_lock()
{
  lock_ = false;
}
inline bool
PrismSwitchAddReq::lock() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchAddReq.lock)
  return lock_;
}
inline void
PrismSwitchAddReq::set_lock(bool value)
{

  lock_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchAddReq.lock)
}

// -------------------------------------------------------------------

// PrismSwitchChangeOwnerReq

// uint32 peer_addr = 1;
inline void
PrismSwitchChangeOwnerReq::clear_peer_addr()
{
  peer_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchChangeOwnerReq::peer_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchChangeOwnerReq.peer_addr)
  return peer_addr_;
}
inline void
PrismSwitchChangeOwnerReq::set_peer_addr(::google::protobuf::uint32 value)
{

  peer_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchChangeOwnerReq.peer_addr)
}

// uint32 peer_port = 2;
inline void
PrismSwitchChangeOwnerReq::clear_peer_port()
{
  peer_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchChangeOwnerReq::peer_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchChangeOwnerReq.peer_port)
  return peer_port_;
}
inline void
PrismSwitchChangeOwnerReq::set_peer_port(::google::protobuf::uint32 value)
{

  peer_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchChangeOwnerReq.peer_port)
}

// uint32 owner_addr = 3;
inline void
PrismSwitchChangeOwnerReq::clear_owner_addr()
{
  owner_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchChangeOwnerReq::owner_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchChangeOwnerReq.owner_addr)
  return owner_addr_;
}
inline void
PrismSwitchChangeOwnerReq::set_owner_addr(::google::protobuf::uint32 value)
{

  owner_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchChangeOwnerReq.owner_addr)
}

// uint32 owner_port = 4;
inline void
PrismSwitchChangeOwnerReq::clear_owner_port()
{
  owner_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchChangeOwnerReq::owner_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchChangeOwnerReq.owner_port)
  return owner_port_;
}
inline void
PrismSwitchChangeOwnerReq::set_owner_port(::google::protobuf::uint32 value)
{

  owner_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchChangeOwnerReq.owner_port)
}

// uint64 owner_mac = 5;
inline void
PrismSwitchChangeOwnerReq::clear_owner_mac()
{
  owner_mac_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64
PrismSwitchChangeOwnerReq::owner_mac() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchChangeOwnerReq.owner_mac)
  return owner_mac_;
}
inline void
PrismSwitchChangeOwnerReq::set_owner_mac(::google::protobuf::uint64 value)
{

  owner_mac_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchChangeOwnerReq.owner_mac)
}

// bool unlock = 6;
inline void
PrismSwitchChangeOwnerReq::clear_unlock()
{
  unlock_ = false;
}
inline bool
PrismSwitchChangeOwnerReq::unlock() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchChangeOwnerReq.unlock)
  return unlock_;
}
inline void
PrismSwitchChangeOwnerReq::set_unlock(bool value)
{

  unlock_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchChangeOwnerReq.unlock)
}

// -------------------------------------------------------------------

// PrismSwitchDeleteReq

// uint32 peer_addr = 1;
inline void
PrismSwitchDeleteReq::clear_peer_addr()
{
  peer_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchDeleteReq::peer_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchDeleteReq.peer_addr)
  return peer_addr_;
}
inline void
PrismSwitchDeleteReq::set_peer_addr(::google::protobuf::uint32 value)
{

  peer_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchDeleteReq.peer_addr)
}

// uint32 peer_port = 2;
inline void
PrismSwitchDeleteReq::clear_peer_port()
{
  peer_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchDeleteReq::peer_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchDeleteReq.peer_port)
  return peer_port_;
}
inline void
PrismSwitchDeleteReq::set_peer_port(::google::protobuf::uint32 value)
{

  peer_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchDeleteReq.peer_port)
}

// -------------------------------------------------------------------

// PrismSwitchLockReq

// uint32 peer_addr = 1;
inline void
PrismSwitchLockReq::clear_peer_addr()
{
  peer_addr_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchLockReq::peer_addr() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchLockReq.peer_addr)
  return peer_addr_;
}
inline void
PrismSwitchLockReq::set_peer_addr(::google::protobuf::uint32 value)
{

  peer_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchLockReq.peer_addr)
}

// uint32 peer_port = 2;
inline void
PrismSwitchLockReq::clear_peer_port()
{
  peer_port_ = 0u;
}
inline ::google::protobuf::uint32
PrismSwitchLockReq::peer_port() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchLockReq.peer_port)
  return peer_port_;
}
inline void
PrismSwitchLockReq::set_peer_port(::google::protobuf::uint32 value)
{

  peer_port_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchLockReq.peer_port)
}

// -------------------------------------------------------------------

// PrismSwitchReply

// sint32 error = 1;
inline void
PrismSwitchReply::clear_error()
{
  error_ = 0;
}
inline ::google::protobuf::int32
PrismSwitchReply::error() const
{
  // @@protoc_insertion_point(field_get:prism.PrismSwitchReply.error)
  return error_;
}
inline void
PrismSwitchReply::set_error(::google::protobuf::int32 value)
{

  error_ = value;
  // @@protoc_insertion_point(field_set:prism.PrismSwitchReply.error)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// @@protoc_insertion_point(namespace_scope)

} // namespace prism

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_prism_5fswitch_2eproto
