// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tls.proto

#include <tls.pb.h>

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace prism {
class TLSStateDefaultTypeInternal {
public:
  ::google::protobuf::internal::ExplicitlyConstructed<TLSState> _instance;
} _TLSState_default_instance_;
} // namespace prism
namespace protobuf_tls_2eproto {
static void
InitDefaultsTLSState()
{
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void *ptr = &::prism::_TLSState_default_instance_;
    new (ptr)::prism::TLSState();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::prism::TLSState::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TLSState = {
    {ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized),
     0, InitDefaultsTLSState},
    {}};

void
InitDefaults()
{
  ::google::protobuf::internal::InitSCC(&scc_info_TLSState.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32
    TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u, // no _has_bits_
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::prism::TLSState,
                                                       _internal_metadata_),
        ~0u, // no _extensions_
        ~0u, // no _oneof_case_
        ~0u, // no _weak_field_map_
        GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::prism::TLSState, buf_),
};
static const ::google::protobuf::internal::MigrationSchema
    schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, sizeof(::prism::TLSState)},
};

static ::google::protobuf::Message const *const file_default_instances[] = {
    reinterpret_cast<const ::google::protobuf::Message *>(
        &::prism::_TLSState_default_instance_),
};

void
protobuf_AssignDescriptors()
{
  AddDescriptors();
  AssignDescriptors("tls.proto", schemas, file_default_instances,
                    TableStruct::offsets, file_level_metadata, NULL, NULL);
}

void
protobuf_AssignDescriptorsOnce()
{
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void
protobuf_RegisterTypes(const ::std::string &) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void
protobuf_RegisterTypes(const ::std::string &)
{
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void
AddDescriptorsImpl()
{
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(
      protodesc_cold) = {
      "\n\ttls.proto\022\005prism\"\027\n\010TLSState\022\013\n\003buf\030\001 "
      "\001(\014b\006proto3"};
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(descriptor, 51);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
      "tls.proto", &protobuf_RegisterTypes);
}

void
AddDescriptors()
{
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() { AddDescriptors(); }
} static_descriptor_initializer;
} // namespace protobuf_tls_2eproto
namespace prism {

// ===================================================================

void
TLSState::InitAsDefaultInstance()
{
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TLSState::kBufFieldNumber;
#endif // !defined(_MSC_VER) || _MSC_VER >= 1900

TLSState::TLSState() : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
  ::google::protobuf::internal::InitSCC(
      &protobuf_tls_2eproto::scc_info_TLSState.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:prism.TLSState)
}
TLSState::TLSState(const TLSState &from)
    : ::google::protobuf::Message(), _internal_metadata_(NULL)
{
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  buf_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.buf().size() > 0) {
    buf_.AssignWithDefault(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        from.buf_);
  }
  // @@protoc_insertion_point(copy_constructor:prism.TLSState)
}

void
TLSState::SharedCtor()
{
  buf_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

TLSState::~TLSState()
{
  // @@protoc_insertion_point(destructor:prism.TLSState)
  SharedDtor();
}

void
TLSState::SharedDtor()
{
  buf_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void
TLSState::SetCachedSize(int size) const
{
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor *
TLSState::descriptor()
{
  ::protobuf_tls_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tls_2eproto::file_level_metadata[kIndexInFileMessages]
      .descriptor;
}

const TLSState &
TLSState::default_instance()
{
  ::google::protobuf::internal::InitSCC(
      &protobuf_tls_2eproto::scc_info_TLSState.base);
  return *internal_default_instance();
}

void
TLSState::Clear()
{
  // @@protoc_insertion_point(message_clear_start:prism.TLSState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  buf_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool
TLSState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream *input)
{
#define DO_(EXPRESSION)                                                        \
  if (!GOOGLE_PREDICT_TRUE(EXPRESSION))                                        \
  goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:prism.TLSState)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p =
        input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second)
      goto handle_unusual;
    switch (
        ::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
    // bytes buf = 1;
    case 1: {
      if (static_cast<::google::protobuf::uint8>(tag) ==
          static_cast<::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
        DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
            input, this->mutable_buf()));
      } else {
        goto handle_unusual;
      }
      break;
    }

    default: {
    handle_unusual:
      if (tag == 0) {
        goto success;
      }
      DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
      break;
    }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:prism.TLSState)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:prism.TLSState)
  return false;
#undef DO_
}

void
TLSState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream *output) const
{
  // @@protoc_insertion_point(serialize_start:prism.TLSState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes buf = 1;
  if (this->buf().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
        1, this->buf(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&
       ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
             ? _internal_metadata_.unknown_fields()
             : _internal_metadata_.default_instance()),
        output);
  }
  // @@protoc_insertion_point(serialize_end:prism.TLSState)
}

::google::protobuf::uint8 *
TLSState::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8 *target) const
{
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:prism.TLSState)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes buf = 1;
  if (this->buf().size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->buf(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&
       ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target =
        ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                 ? _internal_metadata_.unknown_fields()
                 : _internal_metadata_.default_instance()),
            target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prism.TLSState)
  return target;
}

size_t
TLSState::ByteSizeLong() const
{
  // @@protoc_insertion_point(message_byte_size_start:prism.TLSState)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&
       ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
        ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
            (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()
                 ? _internal_metadata_.unknown_fields()
                 : _internal_metadata_.default_instance()));
  }
  // bytes buf = 1;
  if (this->buf().size() > 0) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                          this->buf());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void
TLSState::MergeFrom(const ::google::protobuf::Message &from)
{
  // @@protoc_insertion_point(generalized_merge_from_start:prism.TLSState)
  GOOGLE_DCHECK_NE(&from, this);
  const TLSState *source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TLSState>(
          &from);
  if (source == NULL) {
    // @@protoc_insertion_point(generalized_merge_from_cast_fail:prism.TLSState)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    // @@protoc_insertion_point(generalized_merge_from_cast_success:prism.TLSState)
    MergeFrom(*source);
  }
}

void
TLSState::MergeFrom(const TLSState &from)
{
  // @@protoc_insertion_point(class_specific_merge_from_start:prism.TLSState)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void)cached_has_bits;

  if (from.buf().size() > 0) {

    buf_.AssignWithDefault(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        from.buf_);
  }
}

void
TLSState::CopyFrom(const ::google::protobuf::Message &from)
{
  // @@protoc_insertion_point(generalized_copy_from_start:prism.TLSState)
  if (&from == this)
    return;
  Clear();
  MergeFrom(from);
}

void
TLSState::CopyFrom(const TLSState &from)
{
  // @@protoc_insertion_point(class_specific_copy_from_start:prism.TLSState)
  if (&from == this)
    return;
  Clear();
  MergeFrom(from);
}

bool
TLSState::IsInitialized() const
{
  return true;
}

void
TLSState::Swap(TLSState *other)
{
  if (other == this)
    return;
  InternalSwap(other);
}
void
TLSState::InternalSwap(TLSState *other)
{
  using std::swap;
  buf_.Swap(&other->buf_,
            &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
            GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata
TLSState::GetMetadata() const
{
  protobuf_tls_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tls_2eproto::file_level_metadata[kIndexInFileMessages];
}

// @@protoc_insertion_point(namespace_scope)
} // namespace prism
namespace google {
namespace protobuf {
template <>
GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::prism::TLSState *
Arena::CreateMaybeMessage<::prism::TLSState>(Arena *arena)
{
  return Arena::CreateInternal<::prism::TLSState>(arena);
}
} // namespace protobuf
} // namespace google

// @@protoc_insertion_point(global_scope)
