// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tcp.proto

#ifndef PROTOBUF_INCLUDED_tcp_2eproto
#define PROTOBUF_INCLUDED_tcp_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/extension_set.h> // IWYU pragma: export
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/message.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h> // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tcp_2eproto

namespace protobuf_tcp_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable
      serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
} // namespace protobuf_tcp_2eproto
namespace prism {
class TCPState;
class TCPStateDefaultTypeInternal;
extern TCPStateDefaultTypeInternal _TCPState_default_instance_;
} // namespace prism
namespace google {
namespace protobuf {
template <>
::prism::TCPState *Arena::CreateMaybeMessage<::prism::TCPState>(Arena *);
} // namespace protobuf
} // namespace google
namespace prism {

// ===================================================================

class TCPState
    : public ::google::protobuf::
          Message /* @@protoc_insertion_point(class_definition:prism.TCPState)
                   */
{
public:
  TCPState();
  virtual ~TCPState();

  TCPState(const TCPState &from);

  inline TCPState &
  operator=(const TCPState &from)
  {
    CopyFrom(from);
    return *this;
  }
#if LANG_CXX11
  TCPState(TCPState &&from) noexcept : TCPState() { *this = ::std::move(from); }

  inline TCPState &
  operator=(TCPState &&from) noexcept
  {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from)
        InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
#endif
  static const ::google::protobuf::Descriptor *descriptor();
  static const TCPState &default_instance();

  static void InitAsDefaultInstance(); // FOR INTERNAL USE ONLY
  static inline const TCPState *
  internal_default_instance()
  {
    return reinterpret_cast<const TCPState *>(&_TCPState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;

  void Swap(TCPState *other);
  friend void
  swap(TCPState &a, TCPState &b)
  {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TCPState *
  New() const final
  {
    return CreateMaybeMessage<TCPState>(NULL);
  }

  TCPState *
  New(::google::protobuf::Arena *arena) const final
  {
    return CreateMaybeMessage<TCPState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message &from) final;
  void MergeFrom(const ::google::protobuf::Message &from) final;
  void CopyFrom(const TCPState &from);
  void MergeFrom(const TCPState &from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream *input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream *output) const final;
  ::google::protobuf::uint8 *InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8 *target) const final;
  int
  GetCachedSize() const final
  {
    return _cached_size_.Get();
  }

private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCPState *other);

private:
  inline ::google::protobuf::Arena *
  GetArenaNoVirtual() const
  {
    return NULL;
  }
  inline void *
  MaybeArenaPtr() const
  {
    return NULL;
  }

public:
  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes sendq = 3;
  void clear_sendq();
  static const int kSendqFieldNumber = 3;
  const ::std::string &sendq() const;
  void set_sendq(const ::std::string &value);
#if LANG_CXX11
  void set_sendq(::std::string &&value);
#endif
  void set_sendq(const char *value);
  void set_sendq(const void *value, size_t size);
  ::std::string *mutable_sendq();
  ::std::string *release_sendq();
  void set_allocated_sendq(::std::string *sendq);

  // bytes recvq = 6;
  void clear_recvq();
  static const int kRecvqFieldNumber = 6;
  const ::std::string &recvq() const;
  void set_recvq(const ::std::string &value);
#if LANG_CXX11
  void set_recvq(::std::string &&value);
#endif
  void set_recvq(const char *value);
  void set_recvq(const void *value, size_t size);
  ::std::string *mutable_recvq();
  ::std::string *release_recvq();
  void set_allocated_recvq(::std::string *recvq);

  // uint32 seq = 1;
  void clear_seq();
  static const int kSeqFieldNumber = 1;
  ::google::protobuf::uint32 seq() const;
  void set_seq(::google::protobuf::uint32 value);

  // uint32 ack = 2;
  void clear_ack();
  static const int kAckFieldNumber = 2;
  ::google::protobuf::uint32 ack() const;
  void set_ack(::google::protobuf::uint32 value);

  // uint64 sendq_len = 4;
  void clear_sendq_len();
  static const int kSendqLenFieldNumber = 4;
  ::google::protobuf::uint64 sendq_len() const;
  void set_sendq_len(::google::protobuf::uint64 value);

  // uint64 unsentq_len = 5;
  void clear_unsentq_len();
  static const int kUnsentqLenFieldNumber = 5;
  ::google::protobuf::uint64 unsentq_len() const;
  void set_unsentq_len(::google::protobuf::uint64 value);

  // uint64 recvq_len = 7;
  void clear_recvq_len();
  static const int kRecvqLenFieldNumber = 7;
  ::google::protobuf::uint64 recvq_len() const;
  void set_recvq_len(::google::protobuf::uint64 value);

  // uint32 self_addr = 8;
  void clear_self_addr();
  static const int kSelfAddrFieldNumber = 8;
  ::google::protobuf::uint32 self_addr() const;
  void set_self_addr(::google::protobuf::uint32 value);

  // uint32 self_port = 9;
  void clear_self_port();
  static const int kSelfPortFieldNumber = 9;
  ::google::protobuf::uint32 self_port() const;
  void set_self_port(::google::protobuf::uint32 value);

  // uint32 peer_addr = 10;
  void clear_peer_addr();
  static const int kPeerAddrFieldNumber = 10;
  ::google::protobuf::uint32 peer_addr() const;
  void set_peer_addr(::google::protobuf::uint32 value);

  // uint32 peer_port = 11;
  void clear_peer_port();
  static const int kPeerPortFieldNumber = 11;
  ::google::protobuf::uint32 peer_port() const;
  void set_peer_port(::google::protobuf::uint32 value);

  // uint32 mss = 12;
  void clear_mss();
  static const int kMssFieldNumber = 12;
  ::google::protobuf::uint32 mss() const;
  void set_mss(::google::protobuf::uint32 value);

  // uint32 send_wscale = 13;
  void clear_send_wscale();
  static const int kSendWscaleFieldNumber = 13;
  ::google::protobuf::uint32 send_wscale() const;
  void set_send_wscale(::google::protobuf::uint32 value);

  // uint32 recv_wscale = 14;
  void clear_recv_wscale();
  static const int kRecvWscaleFieldNumber = 14;
  ::google::protobuf::uint32 recv_wscale() const;
  void set_recv_wscale(::google::protobuf::uint32 value);

  // uint32 timestamp = 15;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 15;
  ::google::protobuf::uint32 timestamp() const;
  void set_timestamp(::google::protobuf::uint32 value);

  // uint32 snd_wl1 = 16;
  void clear_snd_wl1();
  static const int kSndWl1FieldNumber = 16;
  ::google::protobuf::uint32 snd_wl1() const;
  void set_snd_wl1(::google::protobuf::uint32 value);

  // uint32 snd_wnd = 17;
  void clear_snd_wnd();
  static const int kSndWndFieldNumber = 17;
  ::google::protobuf::uint32 snd_wnd() const;
  void set_snd_wnd(::google::protobuf::uint32 value);

  // uint32 max_window = 18;
  void clear_max_window();
  static const int kMaxWindowFieldNumber = 18;
  ::google::protobuf::uint32 max_window() const;
  void set_max_window(::google::protobuf::uint32 value);

  // uint32 rcv_wnd = 19;
  void clear_rcv_wnd();
  static const int kRcvWndFieldNumber = 19;
  ::google::protobuf::uint32 rcv_wnd() const;
  void set_rcv_wnd(::google::protobuf::uint32 value);

  // uint32 rcv_wup = 20;
  void clear_rcv_wup();
  static const int kRcvWupFieldNumber = 20;
  ::google::protobuf::uint32 rcv_wup() const;
  void set_rcv_wup(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:prism.TCPState)
private:
  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sendq_;
  ::google::protobuf::internal::ArenaStringPtr recvq_;
  ::google::protobuf::uint32 seq_;
  ::google::protobuf::uint32 ack_;
  ::google::protobuf::uint64 sendq_len_;
  ::google::protobuf::uint64 unsentq_len_;
  ::google::protobuf::uint64 recvq_len_;
  ::google::protobuf::uint32 self_addr_;
  ::google::protobuf::uint32 self_port_;
  ::google::protobuf::uint32 peer_addr_;
  ::google::protobuf::uint32 peer_port_;
  ::google::protobuf::uint32 mss_;
  ::google::protobuf::uint32 send_wscale_;
  ::google::protobuf::uint32 recv_wscale_;
  ::google::protobuf::uint32 timestamp_;
  ::google::protobuf::uint32 snd_wl1_;
  ::google::protobuf::uint32 snd_wnd_;
  ::google::protobuf::uint32 max_window_;
  ::google::protobuf::uint32 rcv_wnd_;
  ::google::protobuf::uint32 rcv_wup_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tcp_2eproto::TableStruct;
};
// ===================================================================

// ===================================================================

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif // __GNUC__
// TCPState

// uint32 seq = 1;
inline void
TCPState::clear_seq()
{
  seq_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::seq() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.seq)
  return seq_;
}
inline void
TCPState::set_seq(::google::protobuf::uint32 value)
{
  seq_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.seq)
}

// uint32 ack = 2;
inline void
TCPState::clear_ack()
{
  ack_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::ack() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.ack)
  return ack_;
}
inline void
TCPState::set_ack(::google::protobuf::uint32 value)
{
  ack_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.ack)
}

// bytes sendq = 3;
inline void
TCPState::clear_sendq()
{
  sendq_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string &
TCPState::sendq() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.sendq)
  return sendq_.GetNoArena();
}
inline void
TCPState::set_sendq(const ::std::string &value)
{
  sendq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:prism.TCPState.sendq)
}
#if LANG_CXX11
inline void
TCPState::set_sendq(::std::string &&value)
{
  sendq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:prism.TCPState.sendq)
}
#endif
inline void
TCPState::set_sendq(const char *value)
{
  GOOGLE_DCHECK(value != NULL);

  sendq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:prism.TCPState.sendq)
}
inline void
TCPState::set_sendq(const void *value, size_t size)
{
  sendq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:prism.TCPState.sendq)
}
inline ::std::string *
TCPState::mutable_sendq()
{
  // @@protoc_insertion_point(field_mutable:prism.TCPState.sendq)
  return sendq_.MutableNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string *
TCPState::release_sendq()
{
  // @@protoc_insertion_point(field_release:prism.TCPState.sendq)

  return sendq_.ReleaseNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void
TCPState::set_allocated_sendq(::std::string *sendq)
{
  if (sendq != NULL) {
  } else {
  }
  sendq_.SetAllocatedNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), sendq);
  // @@protoc_insertion_point(field_set_allocated:prism.TCPState.sendq)
}

// uint64 sendq_len = 4;
inline void
TCPState::clear_sendq_len()
{
  sendq_len_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64
TCPState::sendq_len() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.sendq_len)
  return sendq_len_;
}
inline void
TCPState::set_sendq_len(::google::protobuf::uint64 value)
{
  sendq_len_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.sendq_len)
}

// uint64 unsentq_len = 5;
inline void
TCPState::clear_unsentq_len()
{
  unsentq_len_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64
TCPState::unsentq_len() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.unsentq_len)
  return unsentq_len_;
}
inline void
TCPState::set_unsentq_len(::google::protobuf::uint64 value)
{
  unsentq_len_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.unsentq_len)
}

// bytes recvq = 6;
inline void
TCPState::clear_recvq()
{
  recvq_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string &
TCPState::recvq() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.recvq)
  return recvq_.GetNoArena();
}
inline void
TCPState::set_recvq(const ::std::string &value)
{
  recvq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:prism.TCPState.recvq)
}
#if LANG_CXX11
inline void
TCPState::set_recvq(::std::string &&value)
{
  recvq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:prism.TCPState.recvq)
}
#endif
inline void
TCPState::set_recvq(const char *value)
{
  GOOGLE_DCHECK(value != NULL);

  recvq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:prism.TCPState.recvq)
}
inline void
TCPState::set_recvq(const void *value, size_t size)
{
  recvq_.SetNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char *>(value), size));
  // @@protoc_insertion_point(field_set_pointer:prism.TCPState.recvq)
}
inline ::std::string *
TCPState::mutable_recvq()
{
  // @@protoc_insertion_point(field_mutable:prism.TCPState.recvq)
  return recvq_.MutableNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string *
TCPState::release_recvq()
{
  // @@protoc_insertion_point(field_release:prism.TCPState.recvq)

  return recvq_.ReleaseNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void
TCPState::set_allocated_recvq(::std::string *recvq)
{
  if (recvq != NULL) {
  } else {
  }
  recvq_.SetAllocatedNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited(), recvq);
  // @@protoc_insertion_point(field_set_allocated:prism.TCPState.recvq)
}

// uint64 recvq_len = 7;
inline void
TCPState::clear_recvq_len()
{
  recvq_len_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64
TCPState::recvq_len() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.recvq_len)
  return recvq_len_;
}
inline void
TCPState::set_recvq_len(::google::protobuf::uint64 value)
{
  recvq_len_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.recvq_len)
}

// uint32 self_addr = 8;
inline void
TCPState::clear_self_addr()
{
  self_addr_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::self_addr() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.self_addr)
  return self_addr_;
}
inline void
TCPState::set_self_addr(::google::protobuf::uint32 value)
{
  self_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.self_addr)
}

// uint32 self_port = 9;
inline void
TCPState::clear_self_port()
{
  self_port_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::self_port() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.self_port)
  return self_port_;
}
inline void
TCPState::set_self_port(::google::protobuf::uint32 value)
{
  self_port_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.self_port)
}

// uint32 peer_addr = 10;
inline void
TCPState::clear_peer_addr()
{
  peer_addr_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::peer_addr() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.peer_addr)
  return peer_addr_;
}
inline void
TCPState::set_peer_addr(::google::protobuf::uint32 value)
{
  peer_addr_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.peer_addr)
}

// uint32 peer_port = 11;
inline void
TCPState::clear_peer_port()
{
  peer_port_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::peer_port() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.peer_port)
  return peer_port_;
}
inline void
TCPState::set_peer_port(::google::protobuf::uint32 value)
{
  peer_port_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.peer_port)
}

// uint32 mss = 12;
inline void
TCPState::clear_mss()
{
  mss_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::mss() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.mss)
  return mss_;
}
inline void
TCPState::set_mss(::google::protobuf::uint32 value)
{
  mss_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.mss)
}

// uint32 send_wscale = 13;
inline void
TCPState::clear_send_wscale()
{
  send_wscale_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::send_wscale() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.send_wscale)
  return send_wscale_;
}
inline void
TCPState::set_send_wscale(::google::protobuf::uint32 value)
{
  send_wscale_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.send_wscale)
}

// uint32 recv_wscale = 14;
inline void
TCPState::clear_recv_wscale()
{
  recv_wscale_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::recv_wscale() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.recv_wscale)
  return recv_wscale_;
}
inline void
TCPState::set_recv_wscale(::google::protobuf::uint32 value)
{
  recv_wscale_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.recv_wscale)
}

// uint32 timestamp = 15;
inline void
TCPState::clear_timestamp()
{
  timestamp_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::timestamp() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.timestamp)
  return timestamp_;
}
inline void
TCPState::set_timestamp(::google::protobuf::uint32 value)
{
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.timestamp)
}

// uint32 snd_wl1 = 16;
inline void
TCPState::clear_snd_wl1()
{
  snd_wl1_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::snd_wl1() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.snd_wl1)
  return snd_wl1_;
}
inline void
TCPState::set_snd_wl1(::google::protobuf::uint32 value)
{
  snd_wl1_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.snd_wl1)
}

// uint32 snd_wnd = 17;
inline void
TCPState::clear_snd_wnd()
{
  snd_wnd_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::snd_wnd() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.snd_wnd)
  return snd_wnd_;
}
inline void
TCPState::set_snd_wnd(::google::protobuf::uint32 value)
{
  snd_wnd_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.snd_wnd)
}

// uint32 max_window = 18;
inline void
TCPState::clear_max_window()
{
  max_window_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::max_window() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.max_window)
  return max_window_;
}
inline void
TCPState::set_max_window(::google::protobuf::uint32 value)
{
  max_window_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.max_window)
}

// uint32 rcv_wnd = 19;
inline void
TCPState::clear_rcv_wnd()
{
  rcv_wnd_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::rcv_wnd() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.rcv_wnd)
  return rcv_wnd_;
}
inline void
TCPState::set_rcv_wnd(::google::protobuf::uint32 value)
{
  rcv_wnd_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.rcv_wnd)
}

// uint32 rcv_wup = 20;
inline void
TCPState::clear_rcv_wup()
{
  rcv_wup_ = 0u;
}
inline ::google::protobuf::uint32
TCPState::rcv_wup() const
{
  // @@protoc_insertion_point(field_get:prism.TCPState.rcv_wup)
  return rcv_wup_;
}
inline void
TCPState::set_rcv_wup(::google::protobuf::uint32 value)
{
  rcv_wup_ = value;
  // @@protoc_insertion_point(field_set:prism.TCPState.rcv_wup)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif // __GNUC__

// @@protoc_insertion_point(namespace_scope)

} // namespace prism

// @@protoc_insertion_point(global_scope)

#endif // PROTOBUF_INCLUDED_tcp_2eproto
